version: '3.8'

services:
  # Наш MCP Сервер
  devboost:
    build:
      context: ..
    environment:
      # Подключаемся к тестовой БД
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/testdb
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
    # Команда запуска из требований хакатона
    command: [ "serve" ]

  # Тестовая БД для демонстрации работы инструмента db_profiler
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - "54322:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
